### ISSUE TITLE
Profile pictures fix

### ISSUE THREAD

**Issue by usarana** [sova-software/website#21]
Some people's PFPs are broken in about page, reason being that they were uploaded to Discord CDN and probably deleted to save space. 

(we uploaded them to discord since we were lazy at that point lol)

**Comment by tizu69** [comment]
Also, the Avatar component doesn't have the initials prop set, this should probably generated as a fallback when images are broken

**Comment by usarana** [comment]
It's fine imo

**Comment by tizu69** [comment]
nah, it should actually show initials. atm, it just shows "AB", which doesn't make sense.
[feel free to just yoink the code I wrote for DZCH for this exact purpuse](https://github.com/BROWSium-dev/deezchords/blob/main/src/lib/api/custom/initials.ts)
